// This file was generated by silverstripe/tx-translator from client/lang/src/pl.json.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('pl', {
    "GridFieldQueuedExportButton.DOWNLOADED": "Twój eksport został pobrany."
});
}